" Follow XDG directory specifications (darwin too for convenience)
"let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
"set directory=$XDG_CACHE_HOME/vim
"set viminfo+=n$XDG_CACHE_HOME/viminfo
"set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$XDG_CONFIG_HOME/vim/bundle/vundle

set nocompatible              " be iMproved, required
filetype off                  " required

" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
" Let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'fholgado/minibufexpl.vim'

Plugin 'rodjek/vim-puppet'
Plugin 'vim-ruby/vim-ruby'
Plugin 'davidhalter/jedi-vim'

Plugin 'adonis0147/prettyGuides'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

""" Keyboard shortcuts
map <C-n> :NERDTreeToggle<CR>


""" Plugin config
" Syntax checker colors
hi SignColumn ctermbg=none
hi SyntasticErrorSign ctermfg=1 ctermbg=none
hi SyntasticWarningSign ctermfg=3 ctermbg=none
hi SyntasticStyleErrorSign ctermfg=1 ctermbg=none
hi SyntasticStyleWarningSign ctermfg=3 ctermbg=none
hi SyntasticErrorLine ctermfg=none ctermbg=none
hi SyntasticWarningLine ctermfg=none ctermbg=none
hi SyntasticStyleErrorLine ctermfg=none ctermbg=none
hi SyntasticStyleWarningLine ctermfg=none ctermbg=none
hi SpellBad ctermfg=0 ctermbg=3
hi SpellCap ctermfg=0 ctermbg=1

" MiniBufExpl Colors
hi MBENormal               guifg=#808080 guibg=fg
hi MBEChanged              guifg=#CD5907 guibg=fg
hi MBEVisibleNormal        guifg=#5DC2D6 guibg=fg
hi MBEVisibleChanged       guifg=#F1266F guibg=fg
hi MBEVisibleActiveNormal  guifg=#A6DB29 guibg=fg
hi MBEVisibleActiveChanged guifg=#F1266F guibg=fg

""""""""""
" Number before each line
set number

" Brackets matching
set showmatch

""" Indenting rules
" Set tab character to 4 characters
set tabstop=4
" Use spaces instead of tab
set expandtab
" Indent width for tabs
set shiftwidth=4
" Do smart indentation
set smartindent
" Indent to the same level as the line before, do not interfer with any other
" indenting rules
set autoindent

" Always show current position
set ruler

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

""" Search options
" Ignore case when searching
set ignorecase
" When searching try to be smart about cases 
set smartcase
" Highlight search results
set hlsearch
" Makes search act like search in modern browsers
set incsearch

" Enable syntax highlighting
syntax enable

" Enable code folding, type za to open and close
set foldmethod=indent
set foldlevel=99

" Pretty colors
colorscheme desert
set background=dark

" Always show the status line
set laststatus=2

" Format the status line
set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l

" Enable mouse usage (all modes)
set mouse=a

""""""""""

" Custom functions starts here "
" Returns true if paste mode is enabled
function! HasPaste()
    if &paste
        return 'PASTE MODE  '
    en
    return ''
endfunction

" Custom functions ends here "

""""""""""

